version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ../redis_data:/var/lib/redis
      - /app/node_modules

  db:
    image: postgres:15-alpine
    container_name: psql-kotuko
    env_file:
      - pg_env.txt
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
        
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    command: sh entrypoint.sh
    container_name: express

  

  # mongodb:
  #   image: mongo:6.0
  #   volumes:
  #     - ./mongodb_data:/data/db
  #   ports:
  #     - 27017:27017
  #   container_name: mongo
    
volumes:
  postgres-data:
    name: postgres-data